import { Component } from '@angular/core';
import { ConversationItemComponent } from './conversation-item/conversation-item.component';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'wp-conversation-list',
  standalone: true,
  imports: [ConversationItemComponent,RouterLink],
  templateUrl: './conversation-list.component.html',
  styleUrl: './conversation-list.component.scss',
})
export class ConversationListComponent {
  conversations: Conversation[] = [
    {
      id: 1,
      name: 'Ethan Gonzalez',
      lastMessage: 'You on your way?',
      time: '10:32',
      unread: 2,
      avatar: '../../../assets/images/man-avatar.png',
    },
    {
      id: 2,
      name: 'Bryan Wallace',
      lastMessage: 'Hey, it\'s me',
      time: '10:32',
      unread: 3,
      avatar: '../../../assets/images/man-avatar.png',
    },
    {
      id: 3,
      name: 'Avery Stewart',
      lastMessage: 'I should buy a boat',
      time: '10:32',
      unread: 0,
      avatar: '../../../assets/images/man-avatar.png',
    },
    {
      id: 4,
      name: 'Katie Peterson',
      lastMessage: 'Look at my mukluks!',
      time: '10:32',
      unread: 0,
      avatar: '../../../assets/images/man-avatar.png',
    },
    {
      id: 5,
      name: 'Sophia Johnson',
      lastMessage: 'What are you up to tonight?',
      time: '10:32',
      unread: 1,
      avatar: '../../../assets/images/woman-avatar.png',
    },
    {
      id: 6,
      name: 'Mia Thompson',
      lastMessage: 'I m feeling hungry, want to grab some food?',
      time: '10:32',
      unread: 0,
      avatar: '../../../assets/images/woman-avatar.png',
    },
    {
      id: 7,
      name: 'Liam Wilson',
      lastMessage: 'Did you finish the report?',
      time: '10:32',
      unread: 0,
      avatar: '../../../assets/images/man-avatar.png',
    },
    {
      id: 8,
      name: 'Noah Anderson',
      lastMessage: 'Check out this meme!',
      time: '10:32',
      unread: 5,
      avatar: '../../../assets/images/man-avatar.png',
    },
    {
      id: 9,
      name: 'Emma Garcia',
      lastMessage: 'How was your day?',
      time: '10:32',
      unread: 0,
      avatar: '../../../assets/images/woman-avatar.png',
    },
    {
      id: 10,
      name: 'Olivia Martinez',
      lastMessage: 'I got tickets to the concert!',
      time: '10:32',
      unread: 0,
      avatar: '../../../assets/images/woman-avatar.png',
    },
    {
      id: 11,
      name: 'William Hernandez',
      lastMessage: 'Lets meet up for coffee tomorrow.',
      time: '10:32',
      unread: 0,
      avatar: '../../../assets/images/man-avatar.png',
    },
    {
      id: 12,
      name: 'James Smith',
      lastMessage: 'Remember to pick up milk on your way home.',
      time: '10:32',
      unread: 0,
      avatar: '../../../assets/images/man-avatar.png',
    },
    {
      id: 13,
      name: 'Alexander Taylor',
      lastMessage: 'How about a game of chess?',
      time: '10:32',
      unread: 2,
      avatar: '../../../assets/images/man-avatar.png',
    },
    {
      id: 14,
      name: 'Michael Brown',
      lastMessage: 'I need your help with something urgent.',
      time: '10:32',
      unread: 0,
      avatar: '../../../assets/images/man-avatar.png',
    },
    {
      id: 15,
      name: 'Daniel Rodriguez',
      lastMessage: 'Have you seen the latest episode?',
      time: '10:32',
      unread: 0,
      avatar: '../../../assets/images/man-avatar.png',
    },
    {
      id: 16,
      name: 'David Lee',
      lastMessage: 'Lets plan a trip for the holidays.',
      time: '10:32',
      unread: 0,
      avatar: '../../../assets/images/man-avatar.png',
    },
    {
      id: 17,
      name: 'Sarah Clark',
      lastMessage: 'I m bored, do you want to hang out?',
      time: '10:32',
      unread: 3,
      avatar: '../../../assets/images/woman-avatar.png',
    },
    {
      id: 18,
      name: 'Sophie Lewis',
      lastMessage: 'Just finished my workout, feeling great!',
      time: '10:32',
      unread: 0,
      avatar: '../../../assets/images/woman-avatar.png',
    },
    {
      id: 19,
      name: 'Charlotte Walker',
      lastMessage: 'Lets catch up soon.',
      time: '10:32',
      unread: 0,
      avatar: '../../../assets/images/woman-avatar.png',
    },
    {
      id: 20,
      name: 'Emily Hall',
      lastMessage: 'I m so excited for the party tonight!',
      time: '10:32',
      unread: 1,
      avatar: '../../../assets/images/woman-avatar.png',
    },
    {
      id: 21,
      name: 'Ryan Young',
      lastMessage: 'Have you tried the new restaurant in town?',
      time: '10:32',
      unread: 0,
      avatar: '../../../assets/images/man-avatar.png',
    },
    {
      id: 22,
      name: 'Jacob Evans',
      lastMessage: 'Let s play some video games together.',
      time: '10:32',
      unread: 0,
      avatar: '../../../assets/images/man-avatar.png',
    },
    {
      id: 23,
      name: 'Benjamin Allen',
      lastMessage: 'I have a surprise for you!',
      time: '10:32',
      unread: 0,
      avatar: '../../../assets/images/man-avatar.png',
    },
    {
      id: 24,
      name: 'William Perez',
      lastMessage: 'How was your weekend?',
      time: '10:32',
      unread: 0,
      avatar: '../../../assets/images/man-avatar.png',
    },
    {
      id: 25,
      name: 'Joseph Turner',
      lastMessage: 'Do you want to go for a hike this weekend?',
      time: '10:32',
      unread: 0,
      avatar: '../../../assets/images/man-avatar.png',
    },
    {
      id: 26,
      name: 'Harper Scott',
      lastMessage: 'I m thinking of redecorating my room.',
      time: '10:32',
      unread: 0,
      avatar: '../../../assets/images/woman-avatar.png',
    },
    {
      id: 27,
      name: 'Evelyn Green',
      lastMessage: 'Let s go shopping together.',
      time: '10:32',
      unread: 0,
      avatar: '../../../assets/images/woman-avatar.png',
    },
    {
      id: 28,
      name: 'Aiden Baker',
      lastMessage: 'Can you help me with my homework?',
      time: '10:32',
      unread: 0,
      avatar: '../../../assets/images/man-avatar.png',
    },
    {
      id: 29,
      name: 'Elijah Adams',
      lastMessage: 'I m planning a surprise party for Sarah.',
      time: '10:32',
      unread: 0,
      avatar: '../../../assets/images/man-avatar.png',
    },
    {
      id: 30,
      name: 'Ella Wright',
      lastMessage: 'What do you want for your birthday?',
      time: '10:32',
      unread: 0,
      avatar: '../../../assets/images/woman-avatar.png',
    }
  ];
}

export interface Conversation {
  id: number;
  name: string;
  lastMessage: string;
  time: string;
  unread: number;
  avatar: string;
}
